apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-team-b
  namespace: argocd
spec:
  description: Project for team-b namespace Applications and ApplicationSets

  sourceNamespaces:
    - argocd-team-b

  destinations:
    - namespace: 'argocd-team-b*'
      server: https://kubernetes.default.svc

  sourceRepos:
    - https://github.com/argoproj/argocd-example-apps

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace