apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base/cluster-install
#- ../../namespaces

patches:
- path: overlays/disable-dex.yaml
#- path: overlays/production/argo-cd-cm.yaml
#- path: overlays/production/argocd-cmd-params-cm.yaml
#- path: overlays/production/argocd-rbac-cm.yaml
#- path: overlays/production/argocd-server-service.yaml
#- target:
#    group: apps
#    version: v1
#    kind: Deployment
#    name: argocd-server
#  patch: |
#    - op: add
#      path: /spec/template/spec/containers/0/args/-
#      value: --disable-dex


images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argo-cd/argocd
  newTag: 3.6.0-e2c6063d
